/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/billboard.glb
Author: irons3th (https://sketchfab.com/irons3th)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/billboard-park-932773f38faa41f38e74927b5a5fd08c
Title: Billboard Park
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { Form, Text3dWood, SpotLight } from "./"
import { folder, useControls } from 'leva';


export function Billboard(props) {
  const { nodes, materials } = useGLTF('/models/billboard.glb')
  
  // const { p_red, p_green, p_blue, r_red, r_green, r_blue, distance, angle } = useControls({
  //   position: folder({
  //     p_red: { value: 0.85, min: -10, max: 12, step: 0.01 },
  //     p_green: { value: -1.4, min: -5, max: 20, step: 0.01 },
  //     p_blue: { value: 0.66, min: -10, max: 10, step: 0.01 },
  //   }),

  //   rotation: folder({
  //     r_red: { value: 0, min: -5, max: 5, step: 0.1 },
  //     r_green: { value: 0, min: -5, max: 5, step: 0.1 },
  //     r_blue: { value: 0, min: -5, max: 5, step: 0.1 },
  //   }),
  //   distance: { value: 10, min: -5, max: 15, step: 0.1 },
  //   angle: { value: 0.4, min: 0, max: 5, step: 0.01 },
    
  // })

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.MI_Billboard_AmusementPark_01_inst} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.MI_Billboard_AmusementPark_inst} />
      <mesh receiveShadow geometry={nodes.Object_7.geometry} material={materials['Material.001']}>
        <Text3dWood text={"Contact"} position={[-3.66, 9.68, 0.90]} rotation={[0, 0, 1.1]} size={1.4} bevelSize={0.04}  />
        {/* <Text3dWood position={[p_red, p_green, p_blue]} rotation={[r_red, r_green, r_blue]} size={1.4} bevelSize={0.02}  /> */}
        <Form scale={0.5} position={[3, 12.5, 1]} />
        <Text3dWood text={"Thank"} position={[5.53, 14.8, 0.66]} rotation={[0, 0, -0.1]} size={1} bevelSize={0.04}  />
        <Text3dWood text={"you"} position={[5.7, 13.3, 0.66]} rotation={[0, 0, 0.1]} size={1} bevelSize={0.04}  />
        <Text3dWood text={"for"} position={[7.2, 12.1, 0.66]} rotation={[0, 0, -0.1]} size={1} bevelSize={0.04}  />
        <Text3dWood text={"coming"} position={[5.35, 10.10, 0.66]} rotation={[0, 0, 0.2]} size={1} bevelSize={0.04}  />
        {/* <Text3dWood text={"coming"} position={[p_red, p_green, p_blue]} rotation={[r_red, r_green, r_blue]} size={1} bevelSize={0.04}  /> */}
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.002']}>
        {/* <SpotLight angle={0.4} position={[-0.55, 17.52, 2.99]} rotation={[0.6, 0.0, 0.3]} /> */}
        {/* <SpotLight angle={0.4} position={[5.12, 17.06, 2.52]} rotation={[0.6, 0, -0.2]} /> */}
        <SpotLight distance={3.8} intensity={3} angle={0.4} position={[0.23, 17.39, 2.99]} rotation={[0.7, 0, 0.7]} />
        <SpotLight distance={2.4} intensity={3.5} angle={0.25} position={[5.12, 17.06, 7.38]} rotation={[0.9, 0, -0.3]} />
        <SpotLight distance={10} intensity={0.8} angle={0.24} position={[12, 6.47, 9.12]} rotation={[2.16, 0, -0.4]} />
        {/* <SpotLight distance={distance} intensity={1} angle={angle} position={[p_red, p_green, p_blue]} rotation={[r_red, r_green, r_blue]} /> */}
        <SpotLight distance={10} intensity={1.4} angle={0.23} position={[-7.06, 7.00, 9.12]} rotation={[2.18, 0, 0.4]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/billboard.glb')
