/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 DevLaying.glb
*/
import * as THREE from "three";
import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Dev(props) {
  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/models/DevLaying.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions["LayingIdle"].play()
    console.log(materials)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.0045}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh frustumCulled={false} roughness={0} castShadow receiveShadow name="Body" geometry={nodes.Body.geometry} material={materials.Bodymat} skeleton={nodes.Body.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Bottoms" geometry={nodes.Bottoms.geometry} material={materials.Bottommat} skeleton={nodes.Bottoms.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Eyelashes" geometry={nodes.Eyelashes.geometry} material={materials.Eyelashmat} skeleton={nodes.Eyelashes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Eyes" geometry={nodes.Eyes.geometry} material={materials.Bodymat} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Hair" geometry={nodes.Hair.geometry} material={materials.Hairmat} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Shoes" geometry={nodes.Shoes.geometry} material={materials.Shoesmat} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh frustumCulled={false} castShadow receiveShadow name="Tops" geometry={nodes.Tops.geometry} material={materials.Topmat} skeleton={nodes.Tops.skeleton} />
        </group>
      </group>
    </group>
  )
}

<meshStandardMaterial 
          metalness={0.2} 
          roughness={0.8}   
          color={"white"} 
        />

useGLTF.preload('/DevLaying.glb')
